# Generated by Django 5.2.8 on 2026-03-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medAiapp', '0003_alter_patient_id_alter_pendinguser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_confidence_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_prediction_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_prediction_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='modality',
            field=models.CharField(choices=[('Fracture', 'Bone Fracture'), ('MRI', 'Brain MRI'), ('Skin', 'Skin Lesion'), ('XRay', 'Chest X-Ray')], default='XRay', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
