# Generated by Django 5.2.8 on 2026-03-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medAiapp', '0006_post_alter_pendinguser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='post',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='post',
        ),
        migrations.AlterModelOptions(
            name='pendinguser',
            options={},
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
